name: Init Gradle Wrapper

on:
  workflow_dispatch:
jobs:
  init-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.2

      - name: Commit wrapper files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper
          git commit -m "Add Gradle wrapper 8.2"
          git push
